#!/bin/bash
HERE=`pwd`
DEPTH=../../../..

cd ${DEPTH}/system/bluetooth/bluedroid
# fix for 32bit fb
patch -p0 < ${HERE}/bluetooth.c.patch
cd ${HERE}


cd ${DEPTH}/bootable/recovery/minui
# fix for 32bit fb
patch -p0 < ${HERE}/graphics.c.patch
cd ${HERE}

cd ${DEPTH}/bootable/recovery/utilities
chmod a+x parted
chmod a+x sdparted
chmod a+x fix_permissions
cd ${HERE}

rm -rf ${DEPTH}/system/init

# noobnl/coolya patch https://github.com/cmsgs/android_frameworks_base/commit/91868b3f24f37dc52653aef7e2a11d5f133f0a24
# https://github.com/cmsgs/android_frameworks_base/commit/09aeaa1013e36a15c2e3a9a85580ab0b0eb35b62
cd ${DEPTH}/frameworks/base/telephony/java/com/android/internal/telephony
patch -p0 < ${HERE}/RIL.java.patch
patch -p0 < ${HERE}/RILConstants.java.patch
cd ${HERE}

